# apiVersion: v1
# kind: Secret
# metadata:
#   name: aws-credentials
#   namespace: togglemaster-flag
#   labels:
#     app.kubernetes.io/name: flag-service
#     app.kubernetes.io/component: flag
#     app.kubernetes.io/part-of: togglemaster
# type: Opaque
# data:
#   access-key: ${AWS_ACCESS_KEY_BASE64}
#   secret-access-key: ${AWS_SECRET_KEY_BASE64}
#   session-token: ${AWS_SESSION_TOKEN_BASE64}

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-us-east-1
  namespace: togglemaster-flag
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
          sessionTokenSecretRef:
            name: aws-credentials
            key: session-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flag-service-rds
  namespace: togglemaster-flag
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-us-east-1
    kind: SecretStore
  target:
    name: flag-service-rds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rds!db-256f4b5b-c5d7-40f8-8cdd-504646c98c28
        property: username
    - secretKey: password
      remoteRef:
        key: rds!db-256f4b5b-c5d7-40f8-8cdd-504646c98c28
        property: password
